"""
I have a schedule of trainings which are put into a week. A training is of a certain type and has an intensity, derived from distance, speed ???
--> find a good way to calculate itensity.
Furthermore trainings are executed in Sessions. Session information could be derived from platforms like Garmin Connect to measure success
Sessions should have comments generated by the user telling weither it was hard or not.
Sessions are executed by an Athlete. An athlete has a current state of fitness, which is expressed as VDOT value.

A schedule can be influenced by the user by supplying sessions,  i.e. by an other trainer
A schedule of trainings is based on a bigger training plan which is based on more weeks

"""

import training
from flask import Flask

app = training.create_app()

app.run(debug=True)
